- name: check current cpu usage of cluster
  hosts: "{{ master.group }}:{{ mpi.group }}:{{ slave.group }}"
  gather_facts: no
  vars_files:
   - vars/custom.yml
   - vars/common.yml
   - vars/ec2.yml
   - vars/launch.yml
  tasks:
   - shell: top -bn2 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}'
     register: cpu_usage
   - debug: msg={{ cpu_usage.stdout_lines[1] }}
