---
- name: copy parameter files and scripts, start supervisor daemon, start factoring job
  hosts: '{{ master.group }}'
  gather_facts: no
  vars_files:
   - vars/custom.yml
   - vars/common.yml
   - vars/ec2.yml
   - vars/launch.yml
  pre_tasks:
   - include_vars: vars/factor.yml
     when: test is not defined
   - include_vars: vars/test-factor.yml
     when: test is defined
   - set_fact: params_file_remote='/home/ubuntu/params.{{ my_tag }}'
  roles:
   - factor
