---
- name: terminate ec2 instances
  hosts: localhost
  gather_facts: no
  vars_files: 
   - vars/custom.yml
   - vars/common.yml
   - vars/ec2.yml
   - vars/launch.yml
  roles:
   - { role: terminate, instance: '{{ master }}', tags: ['master'] }
   - { role: terminate, instance: '{{ mpi }}', tags: ['mpi'] }
   - { role: terminate, instance: '{{ slave }}', tags: ['slave'] }
